on:
  pull_request:
    types: 
      - opened
      - closed
      - synchronize
    branches:
      - release/*

 
  workflow_dispatch:
    inputs:
      source:
        description: 'Source Ref (feature branch only, not main)'
        required: true
      target:
        description: 'Release branch (any, pre-* or fix-* for prerelease/hotfix)'
        required: true
        default: 'autorelease'

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  auto-release:
    if: github.event_name == 'pull_request' && (github.event.pull_request.merged || github.event.action != 'closed')
    name: Auto Release
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: codaxio/cdx@main
        with:
          config: cli.config.ts
          load: commands/
          command: |
            release \
              --source ${{ github.event.pull_request.head.ref }} \
              --target ${{ github.event.pull_request.base.ref }} \
              --pr ${{ github.event.pull_request.number }} \
              ${{ github.event.pull_request.merged == true && '--publish' || '' }}

  manual-release:
    if: github.event_name == 'workflow_dispatch'
    name: Manual Release
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: codaxio/cdx@main
        with:
          config: cli.config.ts
          load: commands/
          command: |
            release \
              --source ${{ inputs.source }} \
              --target ${{ format('release/{0}', inputs.target) }} \
              --pr
