on:
  pull_request:
    types: 
      - opened
      - closed
      - synchronize
    branches:
      - release/*

 
  workflow_dispatch:
    inputs:
      source:
        description: 'Source Ref (feature branch only, not main)'
        required: true
      target:
        description: 'Release branch (any, pre-* or fix-* for prerelease/hotfix)'
        required: true
        default: 'autorelease'
      base:
        description: 'Base branch for new release branch (main or another release branch)'
        required: false
        default: 'main'

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read
  repository-projects: read

name: release

jobs:
  auto-release:
    if: github.event_name == 'pull_request' && (github.event.pull_request.merged || github.event.action != 'closed')
    name: Auto Release
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - run: 'gh pr edit ${{ github.event.pull_request.number }}  --add-label="autorelease: pending" --remove-label "autorelease: ready"'
      - uses: actions/checkout@v4

      - uses: codaxio/cdx@main
        with:
          config: cli.config.ts
          load: commands/
          command: |
            release \
              --source ${{ github.event.pull_request.head.ref }} \
              --target ${{ github.event.pull_request.base.ref }} \
              --pr ${{ github.event.pull_request.number }} \
              ${{ github.event.pull_request.merged == true && '--publish' || '' }}

  manual-release:
    if: github.event_name == 'workflow_dispatch'
    name: Manual Release
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: codaxio/cdx@main
        with:
          config: cli.config.ts
          load: commands/
          command: |
            release \
              --source ${{ inputs.source }} \
              --base ${{ inputs.base }} \
              --target ${{ format('release/{0}', inputs.target) }} \
              ${{ inputs.base && format('--base {0}', inputs.base) || '' }} \
              --pr
